version: '3'

services:
  tortoisebot-ros1-real:
    image: hamz115/hamzaferoze2005-cp22:tortoisebot-ros1-real
    container_name: tortoisebot-ros1-real
    privileged: true
    network_mode: "host"
    volumes:
      - /dev/mem:/dev/mem
      - /dev/vchiq:/dev/vchiq
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      - $HOME/.Xauthority:/root/.Xauthority
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://192.168.1.215:11311
      - ROS_HOSTNAME=192.168.1.215
      - ROS_IP=192.168.1.215
    command: bash -c "source /opt/ros/noetic/setup.bash && source /root/catkin_ws/devel/setup.bash && roslaunch tortoisebot_bringup bringup.launch"

  tortoisebot-ros1-slam-real:
    image: hamz115/hamzaferoze2005-cp22:tortoisebot-ros1-slam-real
    container_name: tortoisebot-ros1-slam-real
    privileged: true
    network_mode: "host"
    volumes:
      - /dev/mem:/dev/mem
      - /dev/vchiq:/dev/vchiq
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
      - $HOME/.Xauthority:/root/.Xauthority
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://192.168.1.215:11311
      - ROS_HOSTNAME=192.168.1.215
      - ROS_IP=192.168.1.215
    depends_on:
      - tortoisebot-ros1-real
    command: >
      bash -c "
      source /opt/ros/noetic/setup.bash &&
      source /root/catkin_ws/devel/setup.bash &&
      until rostopic list; do echo Waiting for rosmaster; sleep 1; done &&
      roslaunch tortoisebot_slam slam.launch"